# Create `ess_dd_vars`

ess_dd_vars <- c(
  "Admission_Type", "Admit_Reason_Code", "Admit_Reason_Description",
  "Admit_Source", "AdmitDateTime", "AdmitReasonCombo", "Age", "Age_Units",
  "Age_Years", "AgeGroup", "AgeOrig", "AmbulatoryStatus", "ArrivedDateTime",
  "Assigned_Patient_Location", "BMI", "C_DiagnosisCode_ICD10_Flat",
  "C_DiagnosisCode_ICD9_Flat", "C_DiagnosisCode_SNOMED_Flat", "C_Ethnicity",
  "C_Race", "Category_flat", "CCAvailable", "CCDD", "CCDDCategory_flat",
  "CCDDParsed", "CCInformative", "ChiefComplaintMDTUpdates",
  "ChiefComplaintOrig", "ChiefComplaintParsed", "ChiefComplaintUpdates",
  "ClinicalImpression", "ComboRegionName", "CRace_CEth_Combined_Broad",
  "CRace_CEth_Combined_Narrow", "Create_Cache_ER_Base_Date_Time_Web", "Date",
  "DateOfBirth", "DateProcessed", "DateTimeAdded", "DDAvailable",
  "DDConverted", "DDInformative", "DDParsed", "DDProcessed", "Death_Date_Time",
  "Death_Indicator", "Diagnosis_Coding_System", "Diagnosis_Date_Time_Max",
  "Diagnosis_Date_Time_Min", "Diagnosis_Text", "DiagnosisCombo",
  "DiagnosisDatetime", "DiagnosisPriority", "DiagnosisType", "DiastolicBP",
  "DischargeDiagnosis", "DischargeDiagnosisMDTUpdates",
  "DischargeDiagnosisUpdates", "DischargeDisposition",
  "DischargeDispositionMDTUpdates", "DischargeDispositionUpdates",
  "DischargeDxDescription", "DischargeInstructions", "DispositionCategory",
  "DispositionDateTime", "EssenceID", "Ethnicity", "Ethnicity_Calc",
  "Ethnicity_Description", "ethnicity_flat", "Facility_City",
  "Facility_County", "Facility_ID", "Facility_ID_Type", "Facility_Latitude",
  "Facility_Longitude", "Facility_Name_Treating", "Facility_State",
  "Facility_Street", "Facility_Type_Calc", "Facility_Type_Code",
  "Facility_Type_Text", "FacilityType", "FirstDateTimeAdded", "HalfHour",
  "HasBeenAdmitted", "HasBeenE", "HasBeenI", "HasBeenO", "HealthSystem",
  "Height", "Height_Calc", "Height_Units", "HighestTemp",
  "HomeFacilityDistance", "Hospital", "Hospital_Service", "Hospital_Unit",
  "Hospital_unit_code", "hospital_unit_description", "HospitalName",
  "HospitalRegion", "HospitalState", "HospitalZipCode", "HoursSpentInED",
  "ICD_CCSR_Desc_Flat", "ICD_CCSR_Flat", "ICD_Chapter_Desc_Flat",
  "ICD_Chapter_Flat", "ICD_Diagnosis_Desc_Flat", "ICD_Diagnosis_Flat",
  "ICD_Section_Desc_Flat", "ICD_Section_Flat", "Initial_Acuity",
  "Initial_Temperature_Units", "InitialAcuitySegment", "InitPulseOximetry",
  "InitPulseOximetry_Calc", "InitTemp", "InitTemp_Calc",
  "Insurance_Company_ID", "Insurance_Company_Plan_Type", "InsuranceCoverage",
  "InsurancePlanID", "MedicalRecordNumber", "Medication_List",
  "Medication_Prescribed", "MedicationCode", "MedicationCombo",
  "MedicationDescription", "MedicationList", "Medications", "MedRecNo",
  "Message", "MessageControlID", "MessageDateTime", "MessageTrigger",
  "MessageTrigger_MDT_Updates", "MessageTrigger_Updates", "MessageType",
  "ModeOfArrival", "MonthYear", "NameOfFile", "ObservationDateTime",
  "OnsetDate", "Patient_City", "Patient_Country", "Patient_County",
  "Patient_County_Calc", "Patient_ID", "Patient_State", "Patient_State_Calc",
  "PatientAddress", "PatientClass", "PatientClassList",
  "PatientClassMDTUpdates", "PatientClassUpdates", "PatientFirstInitial",
  "PatientLastInitial", "Physician_ID", "PID", "PregnancyStatus",
  "Previous_Hospital_Unit", "Problem", "Problem_List", "Procedure_Code",
  "Procedure_Code_Naming_System", "Procedure_Text", "ProviderDiagnosis",
  "ProviderDxDescription", "ProviderType", "PRREGION", "QuarterYear", "Race",
  "Race_Calc", "Race_Description", "race_flat", "RecordedDateTime", "Region",
  "Sending_Facility", "SendingFacilityID", "SendingFacilityIDType", "Sex",
  "Shift", "SmokingStatus", "StagingRowID", "SubCategory_flat", "SystolicBP",
  "Time", "TNCategory_flat", "TNSubCategory_flat", "Travel",
  "TriageNotesOrig", "TriageNotesParsed", "UniquePhysicianID", "VisitDate",
  "VisitNumber", "WeekYear", "Weight", "Weight_Calc", "Weight_Units", "Year",
  "ZipCode"
)

usethis::use_data(ess_dd_vars, overwrite = TRUE)
